---
- name: AWS EC2 autoscaling web server
  hosts: all
  remote_user: centos
  become: true


  tasks:
  - name: Put SELinux in permissive mode, logging actions that would be blocked
    selinux:
      policy: targeted
      state: permissive

  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install git
    yum:
      name: git
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Create the www directory
    file:
      path: '/var/www'
      state: directory

  - name: Deploy web code
    git:
      repo: "{{ git_repo }}"
      dest: /var/www

  - name: Configure nginx
    copy:
      src: files/etc/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
    notify:
    - Start nginx

  - name: Enable service nginx
    service:
      name: nginx
      enabled: yes


  handlers:
    - name: Start nginx
      service:
        name: nginx
        state: started

